/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 house.gltf 
Author: ddmclaughlinn (https://sketchfab.com/ddmclaughlinn)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/house1-2317f75971de4b7c9b8d39075db126e2
Title: House1
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export default function House(props) {
  const groupRef = useRef();
  const { nodes, materials } = useGLTF("/house.gltf");

  useFrame(({ mouse }) => {
    if (groupRef.current) {
      const x = (mouse.x * Math.PI) / 10;
      const y = (mouse.y * Math.PI) / 10;
      groupRef.current.rotation.y += (x - groupRef.current.rotation.y) * 0.1;
      groupRef.current.rotation.x += (y - groupRef.current.rotation.x) * 0.1;
    }
  });

  return (
    <group ref={groupRef} {...props} dispose={null}>
      <group position={[10.028, 0.539, 10.803]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh
          geometry={nodes.Object_119.geometry}
          material={materials.Front_door}
          position={[0.603, -1.262, 7.844]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={[0.63, 0.766, 1]}
        />
      </group>
      <group position={[-3.264, -1.669, 5.479]} rotation={[0, -Math.PI / 2, 0]}>
        <group position={[0.867, 1.048, -0.065]} rotation={[0, 0.157, 0]}>
          <mesh
            geometry={nodes.Object_122.geometry}
            material={materials.Verandah}
          />
          <mesh
            geometry={nodes.Object_123.geometry}
            material={materials.Mullians}
          />
          <mesh
            geometry={nodes.Object_124.geometry}
            material={materials.Glass}
          />
          <mesh
            geometry={nodes.Object_126.geometry}
            material={materials.Verandah}
            position={[-0.807, -0.159, -0.005]}
            rotation={[0, -0.154, 0]}
          />
          <mesh
            geometry={nodes.Object_128.geometry}
            material={materials.Brushed_Metal_Dark}
            position={[-0.576, -0.139, -0.069]}
            rotation={[0, 0, -Math.PI]}
          />
        </group>
        <group position={[0.163, 1.048, -0.037]} rotation={[0, 0.001, 0]}>
          <mesh
            geometry={nodes.Object_130.geometry}
            material={materials.Verandah}
          />
          <mesh
            geometry={nodes.Object_131.geometry}
            material={materials.Mullians}
          />
          <mesh
            geometry={nodes.Object_132.geometry}
            material={materials.Glass}
          />
        </group>
        <mesh
          geometry={nodes.Object_134.geometry}
          material={materials.Verandah}
          position={[0.171, 1.005, 0.004]}
        />
      </group>
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials.Verandah}
        position={[-0.2, 0.513, 11.502]}
        rotation={[-2.997, 0, Math.PI]}
        scale={[-1, 1, 1]}
      />
      <mesh
        geometry={nodes.Object_6.geometry}
        material={materials.Verandah}
        position={[-0.2, 0.441, 12]}
        rotation={[-2.997, 0, Math.PI]}
        scale={[-1, 1, 1]}
      />
      <mesh
        geometry={nodes.Object_8.geometry}
        material={materials.Verandah}
        position={[-0.2, 0.373, 12.469]}
        rotation={[-2.997, 0, Math.PI]}
        scale={[-1, 1, 1]}
      />
      <mesh
        geometry={nodes.Object_10.geometry}
        material={materials.material_0}
        position={[4.885, 0.147, 12.84]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        geometry={nodes.Object_12.geometry}
        material={materials.Verandah}
        position={[5.47, 1.536, 12.846]}
        rotation={[-Math.PI / 2, -0.776, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes.Object_14.geometry}
        material={materials.material_0}
        position={[4.63, 2.278, 13.01]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[-0.627, 1, 0.642]}
      />
      <mesh
        geometry={nodes.Object_16.geometry}
        material={materials.material_0}
        position={[4.63, 1.847, 12.916]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
      />
      <mesh
        geometry={nodes.Object_18.geometry}
        material={materials.material_0}
        position={[4.627, 1.669, 13.008]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.044, 0.047, 0.047]}
      />
      <mesh
        geometry={nodes.Object_20.geometry}
        material={materials.Weatherboard}
        position={[2.95, -0.671, 12.794]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.042, 1, 0.042]}
      />
      <mesh
        geometry={nodes.Object_22.geometry}
        material={materials.Weatherboard}
        position={[6.297, -0.671, 12.794]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.042, 1, 0.042]}
      />
      <mesh
        geometry={nodes.Object_24.geometry}
        material={materials.Weatherboard}
        position={[-3.106, -0.671, 11.434]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.042, 1, 0.042]}
      />
      <mesh
        geometry={nodes.Object_26.geometry}
        material={materials.Weatherboard}
        position={[-3.113, -0.671, 8.927]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.042, 1, 0.042]}
      />
      <mesh
        geometry={nodes.Object_28.geometry}
        material={materials.Weatherboard}
        position={[-4.604, -0.671, 8.936]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.042, 1, 0.042]}
      />
      <mesh
        geometry={nodes.Object_30.geometry}
        material={materials.Weatherboard}
        position={[-4.601, -0.671, 7.109]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.042, 1, 0.042]}
      />
      <mesh
        geometry={nodes.Object_32.geometry}
        material={materials.Weatherboard}
        position={[-3.201, -0.671, 3.902]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.042, 1, 0.042]}
      />
      <mesh
        geometry={nodes.Object_34.geometry}
        material={materials.Weatherboard}
        position={[6.292, -0.671, 3.897]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.042, 1, 0.042]}
      />
      <mesh
        geometry={nodes.Object_36.geometry}
        material={materials.Weatherboard}
        position={[-3.214, -0.671, 7.079]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.042, 1, 0.042]}
      />
      <mesh
        geometry={nodes.Object_38.geometry}
        material={materials.Verandah}
        position={[-3.162, 0.522, 11.468]}
        rotation={[-1.568, 1.426, 1.568]}
        scale={[-1, 1, 1]}
      />
      <mesh
        geometry={nodes.Object_40.geometry}
        material={materials.material_0}
        position={[4.631, 2.948, 13.009]}
        rotation={[Math.PI, Math.PI / 2, 0]}
        scale={[0.044, 0.047, 0.047]}
      />
      <mesh
        geometry={nodes.Object_42.geometry}
        material={materials.Verandah}
        position={[-3.785, 0.466, 10.597]}
        rotation={[-1.568, 1.439, -1.574]}
        scale={[-1, 1, 1]}
      />
      <mesh
        geometry={nodes.Object_44.geometry}
        material={materials.Iron}
        position={[3.98, 0.485, 13.1]}
        rotation={[1.568, 1.569, 2.263]}
        scale={[0.144, 0.062, 0.036]}
      />
      <mesh
        geometry={nodes.Object_46.geometry}
        material={materials.Iron}
        position={[5.293, 0.476, 13.1]}
        rotation={[1.568, 1.569, 2.263]}
        scale={[0.144, 0.062, 0.036]}
      />
      <mesh
        geometry={nodes.Object_48.geometry}
        material={materials.Weatherboard}
        position={[-4.618, -0.503, 8.023]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[1.083, 1.083, 1.675]}
      />
      <mesh
        geometry={nodes.Object_50.geometry}
        material={materials.Weatherboard}
        position={[-3.902, -0.461, 8.939]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[1.083, 1.083, 1.675]}
      />
      <mesh
        geometry={nodes.Object_52.geometry}
        material={materials.Weatherboard}
        position={[-3.996, -0.503, 7.104]}
        rotation={[0, -0.001, 0]}
        scale={[1.083, 1.083, 1.675]}
      />
      <mesh
        geometry={nodes.Object_54.geometry}
        material={materials.Iron}
        position={[-4.91, 0.481, 8.053]}
        rotation={[0.002, 0, -2.452]}
        scale={[0.144, 0.062, 0.036]}
      />
      <mesh
        geometry={nodes.Object_56.geometry}
        material={materials.Iron}
        position={[-3.948, 1.299, 8.554]}
        rotation={[0.728, -Math.PI / 2, 0]}
        scale={[0.144, 0.062, 0.036]}
      />
      <mesh
        geometry={nodes.Object_58.geometry}
        material={materials.Weatherboard}
        position={[-1.811, 1.967, 7.765]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[1.083, 1.083, 1.675]}
      />
      <mesh
        geometry={nodes.Object_60.geometry}
        material={materials.Iron}
        position={[0.78, 1.825, 9.553]}
        rotation={[0.43, -Math.PI / 2, 0]}
      />
      <mesh
        geometry={nodes.Object_62.geometry}
        material={materials.Iron}
        position={[3.589, 1.608, 10.689]}
        rotation={[-Math.PI, 0, 2.348]}
      />
      <mesh
        geometry={nodes.Object_64.geometry}
        material={materials.Iron}
        position={[5.599, 1.672, 9.281]}
        rotation={[-Math.PI, 0, 0.8]}
      />
      <mesh
        geometry={nodes.Object_66.geometry}
        material={materials.Iron}
        position={[1.513, 1.585, 5.389]}
        rotation={[2.714, -Math.PI / 2, 0]}
      />
      <mesh
        geometry={nodes.Object_68.geometry}
        material={materials.Iron}
        position={[-3.727, 0.541, 10.512]}
        rotation={[-Math.PI, 0, 3]}
      />
      <mesh
        geometry={nodes.Object_70.geometry}
        material={materials.Iron}
        position={[-0.458, 0.326, 13.304]}
        rotation={[0.156, -Math.PI / 2, 0]}
      />
      <mesh
        geometry={nodes.Object_72.geometry}
        material={materials.Weatherboard}
        position={[-2.588, -0.503, 3.888]}
        rotation={[0, -0.001, 0]}
        scale={[1.083, 1.083, 1.675]}
      />
      <mesh
        geometry={nodes.Object_74.geometry}
        material={materials.Iron}
        position={[-2.316, 1.461, 10.178]}
        rotation={[0, 0, 0.523]}
      />
      <mesh
        geometry={nodes.Object_76.geometry}
        material={materials.Material}
        position={[-2.749, 1.228, 10.911]}
        rotation={[0.43, -Math.PI / 2, 0]}
      />
      <mesh
        geometry={nodes.Object_78.geometry}
        material={materials.Iron}
        position={[-2.933, 1.113, 5.046]}
        rotation={[-Math.PI, 0, 2.602]}
      />
      <mesh
        geometry={nodes.Object_80.geometry}
        material={materials.Wall_paper}
        position={[4.638, -0.23, 9.742]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        scale={[1.223, 1, 1.644]}
      />
      <mesh
        geometry={nodes.Object_82.geometry}
        material={materials.Interior_wall}
        position={[2.972, -0.405, 11.16]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[1.223, 1, 1.644]}
      />
      <mesh
        geometry={nodes.Object_84.geometry}
        material={materials.Verandah}
        position={[3.784, 1.653, 11.172]}
        rotation={[0, 0, -2.326]}
        scale={[1.223, 1, 1.644]}
      />
      <mesh
        geometry={nodes.Object_86.geometry}
        material={materials.Verandah}
        position={[5.483, 1.653, 11.051]}
        rotation={[0, 0, 2.35]}
        scale={[1.223, 1, 1.644]}
      />
      <mesh
        geometry={nodes.Object_88.geometry}
        material={materials.Gutter_board}
        position={[-1.644, -0.44, 7.093]}
        rotation={[-Math.PI / 2, 1.571, 0]}
        scale={[1.223, 1, 1.644]}
      />
      <mesh
        geometry={nodes.Object_90.geometry}
        material={materials.Interior_wall}
        position={[6.288, -0.405, 11.073]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[1.188, 1, 1.618]}
      />
      <mesh
        geometry={nodes.Object_92.geometry}
        material={materials.Iron}
        position={[-3.928, 1.298, 7.471]}
        rotation={[-0.743, -Math.PI / 2, 0]}
        scale={[0.144, 0.062, 0.036]}
      />
      <mesh
        geometry={nodes.Object_94.geometry}
        material={materials.Material}
        position={[-2.748, 1.23, 4.595]}
        rotation={[-0.43, -Math.PI / 2, 0]}
        scale={[-1, 1, 1]}
      />
      <mesh
        geometry={nodes.Object_96.geometry}
        material={materials.Iron}
        position={[-3.717, 0.541, 5.544]}
        rotation={[-Math.PI, 0, 3]}
      />
      <mesh
        geometry={nodes.Object_98.geometry}
        material={materials.Material}
        position={[-3.727, 0.541, 10.512]}
        rotation={[-Math.PI, 0, 3]}
      />
      <mesh
        geometry={nodes.Object_100.geometry}
        material={materials.Blind_Plastic}
        position={[10.041, 0.028, 10.977]}
        rotation={[-Math.PI, Math.PI / 2, 0]}
      />
      <mesh
        geometry={nodes.Object_102.geometry}
        material={materials.Blind_Plastic}
        position={[-0.005, -0.922, 11.336]}
        scale={[2.177, 1.796, 1]}
      />
      <mesh
        geometry={nodes.Object_104.geometry}
        material={materials.Blind_Plastic}
        position={[-1.849, -0.922, 11.336]}
        scale={[2.177, 1.796, 1]}
      />
      <mesh
        geometry={nodes.Object_106.geometry}
        material={materials.Blind_Plastic}
        position={[6.221, -0.95, 11.24]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[2.177, 1.796, 1]}
      />
      <mesh
        geometry={nodes.Object_108.geometry}
        material={materials.Blind_Plastic}
        position={[6.234, -0.95, 6.157]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[2.177, 1.796, 1]}
      />
      <mesh
        geometry={nodes.Object_110.geometry}
        material={materials.Blind_Plastic}
        position={[4.023, -0.944, 12.626]}
        scale={[2.177, 1.796, 1]}
      />
      <mesh
        geometry={nodes.Object_112.geometry}
        material={materials.Blind_Plastic}
        position={[5.346, -0.944, 12.581]}
        scale={[2.177, 1.796, 1]}
      />
      <mesh
        geometry={nodes.Object_114.geometry}
        material={materials.Blind_Plastic}
        position={[-2.959, -0.999, 10.257]}
        rotation={[0, -1.571, 0]}
        scale={[2.177, 1.796, 1]}
      />
      <mesh
        geometry={nodes.Object_116.geometry}
        material={materials.Blind_Plastic}
        position={[-4.47, -0.999, 8.131]}
        rotation={[0, -1.571, 0]}
        scale={[2.177, 1.796, 1]}
      />
      <mesh
        geometry={nodes.Object_136.geometry}
        material={materials.Verandah}
        position={[6.266, -0.429, 8.934]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.404, 1, 0.338]}
      />
      <mesh
        geometry={nodes.Object_138.geometry}
        material={materials.Verandah}
        position={[3.96, -0.445, 12.77]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        scale={[0.395, 1, 0.338]}
      />
      <mesh
        geometry={nodes.Object_140.geometry}
        material={materials.Verandah}
        position={[5.294, -0.449, 12.77]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        scale={[0.395, 1, 0.338]}
      />
      <mesh
        geometry={nodes.Object_142.geometry}
        material={materials.Verandah}
        position={[2.239, -0.148, 11.417]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        scale={[0.426, 1, 0.338]}
      />
      <mesh
        geometry={nodes.Object_144.geometry}
        material={materials.Verandah}
        position={[-3.809, -0.445, 8.899]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        scale={[0.395, 1, 0.338]}
      />
      <mesh
        geometry={nodes.Object_146.geometry}
        material={materials.Verandah}
        position={[-4.572, -0.449, 8.034]}
        rotation={[-Math.PI, 0, Math.PI / 2]}
        scale={[0.395, 1, 0.338]}
      />
      <mesh
        geometry={nodes.Object_148.geometry}
        material={materials.Verandah}
        position={[-3.079, -0.449, 10.178]}
        rotation={[-Math.PI, 0, Math.PI / 2]}
        scale={[0.395, 1, 0.338]}
      />
      <mesh
        geometry={nodes.Object_150.geometry}
        material={materials.Verandah}
        position={[6.273, -0.076, 5.92]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.416, 1, 0.338]}
      />
      <mesh
        geometry={nodes.Object_152.geometry}
        material={materials.Clear_Class}
        position={[2.239, -0.148, 11.417]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        scale={[0.426, 1, 0.338]}
      />
      <mesh
        geometry={nodes.Object_154.geometry}
        material={materials.Frame}
        position={[-1.611, -0.069, 11.405]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        scale={[0.416, 1, 0.338]}
      />
      <mesh
        geometry={nodes.Object_156.geometry}
        material={materials.Frame}
        position={[6.269, -0.093, 11.002]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.416, 1, 0.338]}
      />
      <mesh
        geometry={nodes.Object_158.geometry}
        material={materials.Frame}
        position={[0.232, -0.069, 11.402]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        scale={[0.416, 1, 0.338]}
      />
      <mesh
        geometry={nodes.Object_160.geometry}
        material={materials.Verandah}
        position={[2.177, 0.388, 12.074]}
        rotation={[1.711, 0, -Math.PI / 2]}
        scale={[-1, 1, 1]}
      />
      <mesh
        geometry={nodes.Object_162.geometry}
        material={materials.Verandah}
        position={[2.927, 0.388, 12.074]}
        rotation={[1.711, 0, -Math.PI / 2]}
        scale={[-1, 1, 1]}
      />
      <mesh
        geometry={nodes.Object_164.geometry}
        material={materials.Verandah}
        position={[-0.067, 0.388, 12.074]}
        rotation={[1.711, 0, -Math.PI / 2]}
        scale={[-1, 1, 1]}
      />
      <mesh
        geometry={nodes.Object_166.geometry}
        material={materials.Verandah}
        position={[0.677, 0.388, 12.074]}
        rotation={[1.711, 0, -Math.PI / 2]}
        scale={[-1, 1, 1]}
      />
      <mesh
        geometry={nodes.Object_168.geometry}
        material={materials.Verandah}
        position={[1.421, 0.388, 12.074]}
        rotation={[1.711, 0, -Math.PI / 2]}
        scale={[-1, 1, 1]}
      />
      <mesh
        geometry={nodes.Object_170.geometry}
        material={materials.Verandah}
        position={[-2.977, 0.388, 12.074]}
        rotation={[1.711, 0, -Math.PI / 2]}
        scale={[-1, 1, 1]}
      />
      <mesh
        geometry={nodes.Object_172.geometry}
        material={materials.Verandah}
        position={[-2.313, 0.388, 12.074]}
        rotation={[1.711, 0, -Math.PI / 2]}
        scale={[-1, 1, 1]}
      />
      <mesh
        geometry={nodes.Object_174.geometry}
        material={materials.Verandah}
        position={[-1.582, 0.388, 12.074]}
        rotation={[1.711, 0, -Math.PI / 2]}
        scale={[-1, 1, 1]}
      />
      <mesh
        geometry={nodes.Object_176.geometry}
        material={materials.Verandah}
        position={[-0.823, 0.388, 12.074]}
        rotation={[1.711, 0, -Math.PI / 2]}
        scale={[-1, 1, 1]}
      />
      <mesh
        geometry={nodes.Object_178.geometry}
        material={materials.Gutter_board}
        position={[0.135, 0.335, 12.57]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-1, 1, 1]}
      />
      <mesh
        geometry={nodes.Object_180.geometry}
        material={materials.Verandah}
        position={[-2.735, 0.285, 12.537]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.091, 0.1, 0.083]}
      />
      <mesh
        geometry={nodes.Object_182.geometry}
        material={materials.Verandah}
        position={[-4.313, -0.924, 12.539]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.086, 0.1, 0.086]}
      />
      <mesh
        geometry={nodes.Object_184.geometry}
        material={materials.Verandah}
        position={[-4.314, 0.287, 12.537]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.091, 0.1, 0.083]}
      />
      <mesh
        geometry={nodes.Object_186.geometry}
        material={materials.Verandah}
        position={[-4.313, -0.515, 12.532]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.062, 0.081, 0.062]}
      />
      <mesh
        geometry={nodes.Object_188.geometry}
        material={materials.Verandah}
        position={[-4.313, -1.153, 12.543]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.062, 0.081, 0.062]}
      />
      <mesh
        geometry={nodes.Object_190.geometry}
        material={materials.Verandah}
        position={[-4.312, -1.443, 12.544]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.086, 0.1, 0.086]}
      />
      <mesh
        geometry={nodes.Object_192.geometry}
        material={materials.Verandah}
        position={[-0.901, -0.924, 12.534]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.086, 0.1, 0.086]}
      />
      <mesh
        geometry={nodes.Object_194.geometry}
        material={materials.Verandah}
        position={[-0.901, -0.515, 12.534]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.062, 0.081, 0.062]}
      />
      <mesh
        geometry={nodes.Object_196.geometry}
        material={materials.Verandah}
        position={[-0.901, -1.153, 12.539]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.062, 0.081, 0.062]}
      />
      <mesh
        geometry={nodes.Object_198.geometry}
        material={materials.Verandah}
        position={[-0.901, -1.443, 12.542]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.086, 0.1, 0.086]}
      />
      <mesh
        geometry={nodes.Object_200.geometry}
        material={materials.Verandah}
        position={[-2.736, -0.924, 12.534]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.086, 0.1, 0.086]}
      />
      <mesh
        geometry={nodes.Object_202.geometry}
        material={materials.Verandah}
        position={[-2.736, -0.515, 12.533]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.062, 0.081, 0.062]}
      />
      <mesh
        geometry={nodes.Object_204.geometry}
        material={materials.Verandah}
        position={[-2.736, -1.153, 12.54]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.062, 0.081, 0.062]}
      />
      <mesh
        geometry={nodes.Object_206.geometry}
        material={materials.Verandah}
        position={[-2.736, -1.443, 12.544]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.086, 0.1, 0.086]}
      />
      <mesh
        geometry={nodes.Object_208.geometry}
        material={materials.Verandah}
        position={[0.097, -1.595, 12.533]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-1, 1, 1]}
      />
      <mesh
        geometry={nodes.Object_210.geometry}
        material={materials.Verandah}
        position={[-1.735, -1.595, 12.53]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-1, 1, 1]}
      />
      <mesh
        geometry={nodes.Object_212.geometry}
        material={materials.Verandah}
        position={[0.102, -0.905, 12.537]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-1, 1, 1]}
      />
      <mesh
        geometry={nodes.Object_214.geometry}
        material={materials.wood_floor_deck}
        position={[-2.047, -1.729, 12.45]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        geometry={nodes.Object_216.geometry}
        material={materials.Underhousel}
        position={[5.906, -1.729, 12.889]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        geometry={nodes.Object_218.geometry}
        material={materials.Underhousel}
        position={[6.31, -1.774, 11.12]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        geometry={nodes.Object_220.geometry}
        material={materials.Verandah}
        position={[-3.572, -1.595, 12.532]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-1, 1, 1]}
      />
      <mesh
        geometry={nodes.Object_222.geometry}
        material={materials.Verandah}
        position={[0.935, -0.924, 12.539]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.086, 0.1, 0.086]}
      />
      <mesh
        geometry={nodes.Object_224.geometry}
        material={materials.Verandah}
        position={[0.932, -1.153, 12.539]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.062, 0.081, 0.062]}
      />
      <mesh
        geometry={nodes.Object_226.geometry}
        material={materials.Verandah}
        position={[0.932, -1.443, 12.539]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.086, 0.1, 0.086]}
      />
      <mesh
        geometry={nodes.Object_228.geometry}
        material={materials.Verandah}
        position={[0.936, -0.515, 12.535]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.062, 0.081, 0.062]}
      />
      <mesh
        geometry={nodes.Object_230.geometry}
        material={materials.Verandah}
        position={[-0.902, 0.284, 12.536]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.091, 0.1, 0.083]}
      />
      <mesh
        geometry={nodes.Object_232.geometry}
        material={materials.Verandah}
        position={[0.938, 0.284, 12.536]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.091, 0.1, 0.083]}
      />
      <mesh
        geometry={nodes.Object_234.geometry}
        material={materials.Gutter_board}
        position={[-4.345, 0.305, 10.913]}
        rotation={[0, 1.57, 0]}
        scale={[-1, 1, 1]}
      />
      <mesh
        geometry={nodes.Object_236.geometry}
        material={materials.Verandah}
        position={[-4.311, -1.595, 11.708]}
        rotation={[0, 1.57, 0]}
        scale={[-1, 1, 1]}
      />
      <mesh
        geometry={nodes.Object_238.geometry}
        material={materials.Verandah}
        position={[-4.314, -0.924, 10.714]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.086, 0.1, 0.086]}
      />
      <mesh
        geometry={nodes.Object_240.geometry}
        material={materials.Verandah}
        position={[-4.315, 0.287, 10.711]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.091, 0.1, 0.083]}
      />
      <mesh
        geometry={nodes.Object_242.geometry}
        material={materials.Verandah}
        position={[-4.314, -0.515, 10.707]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.062, 0.081, 0.062]}
      />
      <mesh
        geometry={nodes.Object_244.geometry}
        material={materials.Verandah}
        position={[-4.313, -1.153, 10.718]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.062, 0.081, 0.062]}
      />
      <mesh
        geometry={nodes.Object_246.geometry}
        material={materials.Verandah}
        position={[-4.313, -1.443, 10.718]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.086, 0.1, 0.086]}
      />
      <mesh
        geometry={nodes.Object_248.geometry}
        material={materials.Verandah}
        position={[-4.259, -1.594, 9.894]}
        rotation={[0, 1.57, 0]}
        scale={[-1, 1, 1]}
      />
      <mesh
        geometry={nodes.Object_250.geometry}
        material={materials.Underhousel}
        position={[-4.665, -1.774, 10.938]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        geometry={nodes.Object_252.geometry}
        material={materials.Underhousel}
        position={[1.486, -1.829, 6.829]}
        rotation={[0, 1.571, 0]}
      />
      <mesh
        geometry={nodes.Object_254.geometry}
        material={materials.Verandah}
        position={[-4.323, -0.924, 4.061]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.086, 0.1, 0.086]}
      />
      <mesh
        geometry={nodes.Object_256.geometry}
        material={materials.Verandah}
        position={[-4.324, 0.287, 4.065]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.091, 0.1, 0.083]}
      />
      <mesh
        geometry={nodes.Object_258.geometry}
        material={materials.Verandah}
        position={[-4.323, -0.515, 4.061]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.062, 0.081, 0.062]}
      />
      <mesh
        geometry={nodes.Object_260.geometry}
        material={materials.Verandah}
        position={[-4.322, -1.153, 4.062]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.062, 0.081, 0.062]}
      />
      <mesh
        geometry={nodes.Object_262.geometry}
        material={materials.Verandah}
        position={[-4.322, -1.443, 4.062]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.086, 0.1, 0.086]}
      />
      <mesh
        geometry={nodes.Object_264.geometry}
        material={materials.Gutter_board}
        position={[-4.358, 0.305, 5.626]}
        rotation={[0, 1.57, 0]}
        scale={[-1, 1, 1]}
      />
      <mesh
        geometry={nodes.Object_266.geometry}
        material={materials.Gutter_board}
        position={[-4.997, 0.305, 4.027]}
        scale={[-1, 1, 1]}
      />
      <mesh
        geometry={nodes.Object_268.geometry}
        material={materials.wood_floor_deck}
        position={[-4.665, -1.774, 10.938]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        geometry={nodes.Object_270.geometry}
        material={materials.Verandah}
        position={[-3.697, 0.388, 11.308]}
        rotation={[Math.PI / 2, 0.14, 0]}
        scale={[-1, 1, 1]}
      />
      <mesh
        geometry={nodes.Object_272.geometry}
        material={materials.Verandah}
        position={[-3.697, 0.394, 10.3]}
        rotation={[Math.PI / 2, 0.14, 0]}
        scale={[-1, 1, 1]}
      />
      <mesh
        geometry={nodes.Object_274.geometry}
        material={materials.Verandah}
        position={[-3.697, 0.394, 9.062]}
        rotation={[Math.PI / 2, 0.14, 0]}
        scale={[-1, 1, 1]}
      />
      <mesh
        geometry={nodes.Object_276.geometry}
        material={materials.Verandah}
        position={[-4.32, -1.594, 6.289]}
        rotation={[0, 1.57, 0]}
        scale={[-1, 1, 1]}
      />
      <mesh
        geometry={nodes.Object_278.geometry}
        material={materials.Iron}
        position={[-3.813, 0.457, 3.99]}
        scale={[-1, 1, 1]}
      />
      <mesh
        geometry={nodes.Object_280.geometry}
        material={materials.Material}
        position={[-3.872, 0.509, 3.975]}
        rotation={[0, 0, 0.013]}
        scale={[-1, 1, 1]}
      />
      <mesh
        geometry={nodes.Object_282.geometry}
        material={materials.Frame}
        position={[1.486, -1.829, 6.829]}
        rotation={[0, 1.571, 0]}
      />
      <mesh
        geometry={nodes.Object_284.geometry}
        material={materials.Verandah}
        position={[-3.757, 0.45, 11.852]}
        rotation={[1.631, 0.076, -0.638]}
        scale={[-1, 1, 1]}
      />
      <mesh
        geometry={nodes.Object_286.geometry}
        material={materials.Material}
        position={[1.486, -4.274, 6.829]}
        rotation={[0, 1.571, 0]}
      />
      <mesh
        geometry={nodes.Object_288.geometry}
        material={materials.Verandah}
        position={[0.179, -1.275, 12.536]}
        rotation={[3.141, 0, -Math.PI / 2]}
        scale={[-1, 1, 0.704]}
      />
      <mesh
        geometry={nodes.Object_290.geometry}
        material={materials.Verandah}
        position={[0.018, -1.275, 12.533]}
        rotation={[3.141, 0, -Math.PI / 2]}
        scale={[-1, 1, 0.704]}
      />
      <mesh
        geometry={nodes.Object_292.geometry}
        material={materials.Verandah}
        position={[-0.126, -1.275, 12.533]}
        rotation={[3.141, 0, -Math.PI / 2]}
        scale={[-1, 1, 0.704]}
      />
      <mesh
        geometry={nodes.Object_294.geometry}
        material={materials.Verandah}
        position={[-0.282, -1.275, 12.535]}
        rotation={[3.141, 0, -Math.PI / 2]}
        scale={[-1, 1, 0.704]}
      />
      <mesh
        geometry={nodes.Object_296.geometry}
        material={materials.Verandah}
        position={[-0.429, -1.275, 12.537]}
        rotation={[3.141, 0, -Math.PI / 2]}
        scale={[-1, 1, 0.704]}
      />
      <mesh
        geometry={nodes.Object_298.geometry}
        material={materials.Verandah}
        position={[-0.579, -1.275, 12.538]}
        rotation={[3.141, 0, -Math.PI / 2]}
        scale={[-1, 1, 0.704]}
      />
      <mesh
        geometry={nodes.Object_300.geometry}
        material={materials.Verandah}
        position={[-0.722, -1.275, 12.537]}
        rotation={[3.141, 0, -Math.PI / 2]}
        scale={[-1, 1, 0.704]}
      />
      <mesh
        geometry={nodes.Object_302.geometry}
        material={materials.Verandah}
        position={[0.321, -1.275, 12.537]}
        rotation={[3.141, 0, -Math.PI / 2]}
        scale={[-1, 1, 0.704]}
      />
      <mesh
        geometry={nodes.Object_304.geometry}
        material={materials.Verandah}
        position={[0.473, -1.275, 12.537]}
        rotation={[3.141, 0, -Math.PI / 2]}
        scale={[-1, 1, 0.704]}
      />
      <mesh
        geometry={nodes.Object_306.geometry}
        material={materials.Verandah}
        position={[0.616, -1.275, 12.537]}
        rotation={[3.141, 0, -Math.PI / 2]}
        scale={[-1, 1, 0.704]}
      />
      <mesh
        geometry={nodes.Object_308.geometry}
        material={materials.Verandah}
        position={[0.77, -1.275, 12.537]}
        rotation={[3.141, 0, -Math.PI / 2]}
        scale={[-1, 1, 0.704]}
      />
      <mesh
        geometry={nodes.Object_310.geometry}
        material={materials.Roof_edging}
        position={[3.551, 0.432, 13.189]}
        rotation={[2.211, 0, -Math.PI / 2]}
        scale={[-1, 1, 0.704]}
      />
      <mesh
        geometry={nodes.Object_312.geometry}
        material={materials.Roof_edging}
        position={[4.409, 0.465, 13.126]}
        rotation={[2.215, 0, -Math.PI / 2]}
        scale={[-1, 1, 0.704]}
      />
      <mesh
        geometry={nodes.Object_314.geometry}
        material={materials.Roof_edging}
        position={[4.068, 0.662, 12.87]}
        rotation={[2.207, -0.004, 0.004]}
        scale={[-1, 1, 0.704]}
      />
      <mesh
        geometry={nodes.Object_316.geometry}
        material={materials.Roof_edging}
        position={[4.865, 0.423, 13.189]}
        rotation={[2.211, 0, -Math.PI / 2]}
        scale={[-1, 1, 0.704]}
      />
      <mesh
        geometry={nodes.Object_318.geometry}
        material={materials.Roof_edging}
        position={[5.723, 0.455, 13.126]}
        rotation={[2.215, 0, -Math.PI / 2]}
        scale={[-1, 1, 0.704]}
      />
      <mesh
        geometry={nodes.Object_320.geometry}
        material={materials.Roof_edging}
        position={[5.382, 0.652, 12.87]}
        rotation={[2.207, -0.004, 0.004]}
        scale={[-1, 1, 0.704]}
      />
      <mesh
        geometry={nodes.Object_322.geometry}
        material={materials.Roof_edging}
        position={[-4.987, 0.409, 7.626]}
        rotation={[1.571, 0.638, 0]}
        scale={[-1, 1, 0.704]}
      />
      <mesh
        geometry={nodes.Object_324.geometry}
        material={materials.Roof_edging}
        position={[-4.936, 0.46, 8.488]}
        rotation={[1.571, 0.644, 0]}
        scale={[-1, 1, 0.704]}
      />
      <mesh
        geometry={nodes.Object_326.geometry}
        material={materials.Roof_edging}
        position={[-4.679, 0.657, 8.148]}
        rotation={[1.576, 0.636, 1.571]}
        scale={[-1, 1, 0.704]}
      />
      <mesh
        geometry={nodes.Object_328.geometry}
        material={materials.Material}
        position={[-2.282, 0.454, 7.696]}
        rotation={[2.454, -0.876, 2.594]}
      />
      <mesh
        geometry={nodes.Object_330.geometry}
        material={materials.material_0}
        position={[-2.305, 0.437, 8.357]}
        rotation={[0.653, -0.838, 0.531]}
      />
      <mesh
        geometry={nodes.Object_332.geometry}
        material={materials.Roof_edging}
        position={[-1.927, 1.678, 8.574]}
        rotation={[1.576, 0.636, 1.571]}
        scale={[-1, 1, 0.704]}
      />
      <mesh
        geometry={nodes.Object_334.geometry}
        material={materials.Roof_edging}
        position={[-1.69, 1.678, 7.15]}
        rotation={[1.576, 0.636, 1.571]}
        scale={[-1, 1, 0.704]}
      />
      <mesh
        geometry={nodes.Object_336.geometry}
        material={materials.Roof_edging}
        position={[-1.927, 1.679, 6.72]}
        rotation={[1.576, 0.636, 1.571]}
        scale={[-1, 1, 0.704]}
      />
      <mesh
        geometry={nodes.Object_338.geometry}
        material={materials.Verandah}
        position={[-4.163, 0.113, 12.587]}
        rotation={[Math.PI / 2, -0.432, 0]}
        scale={[0.075, 0.9, 0.075]}
      />
      <mesh
        geometry={nodes.Object_340.geometry}
        material={materials.Verandah}
        position={[-0.749, 0.112, 12.588]}
        rotation={[Math.PI / 2, -0.432, 0]}
        scale={[0.075, 0.9, 0.075]}
      />
      <mesh
        geometry={nodes.Object_342.geometry}
        material={materials.Verandah}
        position={[3.558, 0.047, 13.052]}
        rotation={[2.003, 0, Math.PI / 2]}
        scale={[0.083, 1, 0.083]}
      />
      <mesh
        geometry={nodes.Object_344.geometry}
        material={materials.Verandah}
        position={[4.891, 0.049, 13.052]}
        rotation={[2.003, 0, Math.PI / 2]}
        scale={[0.083, 1, 0.083]}
      />
      <mesh
        geometry={nodes.Object_346.geometry}
        material={materials.Verandah}
        position={[4.358, 0.058, 13.057]}
        rotation={[2.003, 0, Math.PI / 2]}
        scale={[0.083, 1, 0.083]}
      />
      <mesh
        geometry={nodes.Object_348.geometry}
        material={materials.Verandah}
        position={[5.689, 0.05, 13.052]}
        rotation={[2.003, 0, Math.PI / 2]}
        scale={[0.083, 1, 0.083]}
      />
      <mesh
        geometry={nodes.Object_350.geometry}
        material={materials.Verandah}
        position={[-4.862, 0.042, 7.623]}
        rotation={[Math.PI / 2, 0.432, Math.PI]}
        scale={[0.083, 1, 0.083]}
      />
      <mesh
        geometry={nodes.Object_352.geometry}
        material={materials.Verandah}
        position={[-4.862, 0.043, 8.445]}
        rotation={[Math.PI / 2, 0.432, Math.PI]}
        scale={[0.083, 1, 0.083]}
      />
      <mesh
        geometry={nodes.Object_354.geometry}
        material={materials.Verandah}
        position={[-4.36, 0.112, 10.868]}
        rotation={[1.139, 0, -Math.PI / 2]}
        scale={[0.075, 0.9, 0.075]}
      />
      <mesh
        geometry={nodes.Object_356.geometry}
        material={materials.Verandah}
        position={[-2.584, 0.112, 12.588]}
        rotation={[Math.PI / 2, -0.432, 0]}
        scale={[0.075, 0.9, 0.075]}
      />
      <mesh
        geometry={nodes.Object_358.geometry}
        material={materials.Verandah}
        position={[1.09, 0.112, 12.586]}
        rotation={[Math.PI / 2, -0.432, 0]}
        scale={[0.075, 0.9, 0.075]}
      />
      <mesh
        geometry={nodes.Object_360.geometry}
        material={materials.Verandah}
        position={[-2.887, 0.112, 12.587]}
        rotation={[Math.PI / 2, -0.432, 0]}
        scale={[0.075, 0.9, 0.075]}
      />
      <mesh
        geometry={nodes.Object_362.geometry}
        material={materials.Verandah}
        position={[-1.054, 0.113, 12.587]}
        rotation={[Math.PI / 2, -0.432, 0]}
        scale={[0.075, 0.9, 0.075]}
      />
      <mesh
        geometry={nodes.Object_364.geometry}
        material={materials.Verandah}
        position={[0.787, 0.112, 12.586]}
        rotation={[Math.PI / 2, -0.432, 0]}
        scale={[0.075, 0.9, 0.075]}
      />
      <mesh
        geometry={nodes.Object_366.geometry}
        material={materials.Verandah}
        position={[-4.358, 0.113, 12.38]}
        rotation={[2.003, 0, Math.PI / 2]}
        scale={[0.075, 0.9, 0.075]}
      />
      <mesh
        geometry={nodes.Object_368.geometry}
        material={materials.Verandah}
        position={[-4.36, 0.112, 10.554]}
        rotation={[2.003, 0, Math.PI / 2]}
        scale={[0.075, 0.9, 0.075]}
      />
      <mesh
        geometry={nodes.Object_370.geometry}
        material={materials.Verandah}
        position={[3.553, 0.145, 12.84]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        geometry={nodes.Object_372.geometry}
        material={materials.material_0}
        position={[-5.105, 0.238, 8.448]}
        rotation={[Math.PI, 0, Math.PI / 2]}
      />
      <mesh
        geometry={nodes.Object_374.geometry}
        material={materials.material_0}
        position={[-4.65, 0.141, 7.625]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        geometry={nodes.Object_376.geometry}
        material={materials.material_0}
        position={[4.362, 0.243, 13.295]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
      />
      <mesh
        geometry={nodes.Object_378.geometry}
        material={materials.material_0}
        position={[5.693, 0.243, 13.295]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
      />
      <mesh
        geometry={nodes.Object_380.geometry}
        material={materials.Verandah}
        position={[-4.37, 0.112, 4.221]}
        rotation={[1.139, 0, -Math.PI / 2]}
        scale={[0.075, 0.9, 0.075]}
      />
      <mesh
        geometry={nodes.Object_382.geometry}
        material={materials.Verandah}
        position={[-4.171, 0.113, 4.01]}
        rotation={[Math.PI / 2, -0.432, 0]}
        scale={[0.075, 0.9, 0.075]}
      />
      <mesh
        geometry={nodes.Object_384.geometry}
        material={materials.Iron}
        position={[6.479, 0.806, 11.703]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        geometry={nodes.Object_386.geometry}
        material={materials.Iron}
        position={[-1.98, 0.806, 11.341]}
      />
      <mesh
        geometry={nodes.Object_388.geometry}
        material={materials.Iron}
        position={[-1.71, 0.357, 12.322]}
      />
      <mesh
        geometry={nodes.Object_390.geometry}
        material={materials.Iron}
        position={[3.554, 1.476, 10.014]}
        rotation={[2.94, -1.097, 2.215]}
      />
      <mesh
        geometry={nodes.Object_392.geometry}
        material={materials.Iron}
        position={[-4.517, 0.357, 5.165]}
      />
      <mesh
        geometry={nodes.Object_394.geometry}
        material={materials.Gutter_board}
        position={[3.915, 1.75, 12.944]}
        rotation={[Math.PI / 2, -0.783, -Math.PI / 2]}
        scale={[-1, 1, 1]}
      />
      <mesh
        geometry={nodes.Object_396.geometry}
        material={materials.Gutter_board}
        position={[5.589, 1.579, 12.94]}
        rotation={[-Math.PI / 2, -0.775, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes.Object_398.geometry}
        material={materials.Gutter_board}
        position={[-4.649, 1.202, 7.509]}
        rotation={[-0.722, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_400.geometry}
        material={materials.Gutter_board}
        position={[-0.2, 0.814, 11.494]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-1, 1, 1]}
      />
      <mesh
        geometry={nodes.Object_402.geometry}
        material={materials.Gutter_board}
        position={[-3.181, 0.78, 10.228]}
        rotation={[0, -1.57, 0]}
        scale={[-1, 1, 1]}
      />
      <mesh
        geometry={nodes.Object_404.geometry}
        material={materials.Gutter_board}
        position={[2.926, 0.814, 9.822]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[-1, 1, 1]}
      />
      <mesh
        geometry={nodes.Object_406.geometry}
        material={materials.Gutter_board}
        position={[-3.91, 0.794, 7.103]}
        scale={[-1, 1, 1]}
      />
      <mesh
        geometry={nodes.Object_408.geometry}
        material={materials.Gutter_board}
        position={[-1.986, 2.04, 9.047]}
        rotation={[-2.711, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.Object_410.geometry}
        material={materials.Gutter_board}
        position={[-1.986, 2.046, 6.494]}
        rotation={[-0.43, 0, 0]}
        scale={[-1, 1, 1]}
      />
      <mesh
        geometry={nodes.Object_412.geometry}
        material={materials.Gutter_board}
        position={[-3.243, 0.789, 5.81]}
        rotation={[0, -1.57, 0]}
        scale={[-1, 1, 1]}
      />
      <mesh
        geometry={nodes.Object_414.geometry}
        material={materials.Gutter_board}
        position={[0.336, 0.812, 3.885]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        geometry={nodes.Object_416.geometry}
        material={materials.Gutter_board}
        position={[6.323, 0.82, 9.822]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        geometry={nodes.Object_418.geometry}
        material={materials.Gutter_board}
        position={[-3.814, 0.778, 8.923]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-1, 1, 1]}
      />
      <mesh
        geometry={nodes.Object_420.geometry}
        material={materials.Gutter_board}
        position={[-3.91, 0.796, 8.938]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        geometry={nodes.Object_422.geometry}
        material={materials.Gutter_board}
        position={[-3.814, 0.778, 7.111]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-1, 1, 1]}
      />
      <mesh
        geometry={nodes.Object_424.geometry}
        material={materials.Verandah}
        position={[3.811, 1.545, 12.898]}
        rotation={[-Math.PI / 2, 0.795, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes.Object_426.geometry}
        material={materials.Material}
        position={[5.683, 1.6, 12.953]}
        rotation={[-Math.PI / 2, -0.772, -Math.PI / 2]}
        scale={[1, 1.905, 1.905]}
      />
      <mesh
        geometry={nodes.Object_428.geometry}
        material={materials.Material}
        position={[3.724, 1.801, 12.953]}
        rotation={[Math.PI / 2, -0.774, Math.PI / 2]}
        scale={[1, 1.905, 1.905]}
      />
      <mesh
        geometry={nodes.Object_430.geometry}
        material={materials.Material}
        position={[-1.99, 1.989, 9.169]}
        rotation={[-2.712, 0, Math.PI]}
        scale={[1, 1.905, 1.905]}
      />
      <mesh
        geometry={nodes.Object_432.geometry}
        material={materials.Material}
        position={[-1.993, 1.989, 6.34]}
        rotation={[-0.43, 0, 0]}
        scale={[-1, 1.905, 1.905]}
      />
      <mesh
        geometry={nodes.Object_434.geometry}
        material={materials.Material}
        position={[-4.655, 1.553, 8.231]}
        rotation={[-2.412, 0, Math.PI]}
        scale={[1, 1.905, 1.905]}
      />
      <mesh
        geometry={nodes.Object_436.geometry}
        material={materials.Material}
        position={[-4.655, 1.54, 7.782]}
        rotation={[-0.789, 0, 0]}
        scale={[-1, 1.905, 1.905]}
      />
      <mesh
        geometry={nodes.Object_438.geometry}
        material={materials.Material}
        position={[1.641, 2.674, 7.75]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[1, 1, 4.08]}
      />
      <mesh
        geometry={nodes.Object_440.geometry}
        material={materials.Material}
        position={[4.652, 2.693, 10.996]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[1, 1, 4.08]}
      />
      <mesh
        geometry={nodes.Object_442.geometry}
        material={materials.Material}
        position={[5.409, 1.932, 6.013]}
        rotation={[2.711, 0.404, -2.774]}
        scale={[1, 1, 4.08]}
      />
      <mesh
        geometry={nodes.Object_444.geometry}
        material={materials.Material}
        position={[-3.125, 1.756, 8.006]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[1, 1, 4.08]}
      />
      <mesh
        geometry={nodes.Object_446.geometry}
        material={materials.Weatherboard}
        position={[3.533, -0.299, 11.402]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[1.083, 1.083, 1.675]}
      />
      <mesh
        geometry={nodes.Object_448.geometry}
        material={materials.Weatherboard}
        position={[-3.122, -0.503, 10.631]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[1.083, 1.083, 1.675]}
      />
      <mesh
        geometry={nodes.Object_450.geometry}
        material={materials.Weatherboard}
        position={[2.928, -0.503, 11.995]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[1.083, 1.083, 1.675]}
      />
      <mesh
        geometry={nodes.Object_452.geometry}
        material={materials.Weatherboard}
        position={[-3.214, -0.503, 6.256]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[1.083, 1.083, 1.675]}
      />
    </group>
  );
}

useGLTF.preload("/house.gltf");
